knife4j:
  enable: true # 是否启用 knife4j 增强,如果只是使用 knife4j 的 UI,则可以关闭
  openapi:
    group:
      test:
        group-name: 网页前端接口
        api-rule: package
        api-rule-resources:
          - com.yy.controller.pc
      common:
        group-name: 公共接口
        api-rule: package
        api-rule-resources:
          - com.yy.controller.common
    title: 接口文档
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.yy.pojo
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com              # QQ 邮箱的 SMTP 服务器
    port: 587                      # QQ 邮箱的 SMTP 端口号
    username: 2893127039@qq.com    # 发件人的 QQ 邮箱账号
    password: xmxcnsnoarfydgea   # 发件人邮箱的 SMTP 授权码（注意不是密码）
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    database: 2
  rabbitmq:
    host: 192.168.16.16
    port: 5672
    username: blog
    password: 123
    virtual-host: /blog

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效 默认2小时
  timeout: 7200
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
## x-file-store 文件存储
dromara:
  x-file-storage: #文件存储配置
    default-platform: aliyun-oss-1 #默认使用的存储平台
    aliyun-oss:
      - platform: aliyun-oss-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: LTAI5tGrKDvwyA9E4sEJzCEu
        secret-key: BrySY7Xn3exR7rcDUcp0Gzty0a4FdZ
        end-point: oss-cn-beijing.aliyuncs.com
        bucket-name: blog009
        domain: https://blog009.oss-cn-beijing.aliyuncs.com/ # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: os/ # 基础路径
blog:
  jwt:
    secret: asdasd
    expire: 720000
  maxCount: 3
